export const FETCH_START = 'products/fetchStart'
export const FETCH_END = 'products/fetchEnd'
export const ERROR = 'products/error'
export const ADD_TO_CART = 'products/addToCart'
export const REMOVE_CART = 'products/removeCart'
